name: dotTEST Simple Workflow

# Specifies the name of the GitHub events that trigger the workflow.
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ parse_coverage_report ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # Specifies the name of the job.
  RunCodeAnalysisWithDotTEST:
    # Specifies required permissions for upload-sarif action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

##      # Runs code analysis with dotTEST.
#      - name: Static Analysis with Parasoft dotTEST
#        id: dottest-sa
##        # Specifies the action to run.
#        uses: parasoft/run-dottest-action@2.0.1
#        with:
#          installDir: 'E:\Parasoft\Products\DOTTEST\2024.1'
#          testConfig: '.\dottest_settings.properties'
#          solution: '.\BankExample.NET.sln'
#          settings: '.\localsettings.properties'
#          reportDir: '.\reports\dottest\static'
#          sarifMode: 'legacy'

      - name: Unit Test with Parasoft dotTEST
        id: dottest-ut
        uses: parasoft/run-dottest-action@2.0.1
        with:
          installDir: 'E:\Parasoft\Products\DOTTEST\2024.1'
          testConfig: 'builtin://Run VSTest Tests with Coverage'
          solution: '.\BankExample.NET.WithTests.sln'
          settings: '.\localsettings.properties'
          reportDir: '.\reports\dottest\ut'

      - name: Generate The Structure of Summary Details Table
#        uses: ReneeLYF/parasoft-covergae-action-dev@main
        uses: parasoft/parasoft-coverage-action@jason_cicd961&&cicd983
        with:
          report: "**/dottest/ut/coverage.xml"
#          parasoftToolOrJavaRootPath: ""